"""Initial schema with Voter model

Revision ID: 6a966ece3941
Revises:
Create Date: 2026-02-04 13:07:21.954653

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = "6a966ece3941"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "voters",
        sa.Column("voter_registration_number", sa.String(), nullable=False),
        sa.Column("county", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("status_reason", sa.String(), nullable=True),
        sa.Column("last_name", sa.String(), nullable=True),
        sa.Column("first_name", sa.String(), nullable=True),
        sa.Column("middle_name", sa.String(), nullable=True),
        sa.Column("suffix", sa.String(), nullable=True),
        sa.Column("birth_year", sa.String(), nullable=True),
        sa.Column("residence_street_number", sa.String(), nullable=True),
        sa.Column("residence_pre_direction", sa.String(), nullable=True),
        sa.Column("residence_street_name", sa.String(), nullable=True),
        sa.Column("residence_street_type", sa.String(), nullable=True),
        sa.Column("residence_post_direction", sa.String(), nullable=True),
        sa.Column("residence_apt_unit_number", sa.String(), nullable=True),
        sa.Column("residence_city", sa.String(), nullable=True),
        sa.Column("residence_zipcode", sa.String(), nullable=True),
        sa.Column("county_precinct", sa.String(), nullable=True),
        sa.Column("county_precinct_description", sa.String(), nullable=True),
        sa.Column("municipal_precinct", sa.String(), nullable=True),
        sa.Column("municipal_precinct_description", sa.String(), nullable=True),
        sa.Column("congressional_district", sa.String(), nullable=True),
        sa.Column("state_senate_district", sa.String(), nullable=True),
        sa.Column("state_house_district", sa.String(), nullable=True),
        sa.Column("judicial_district", sa.String(), nullable=True),
        sa.Column("county_commission_district", sa.String(), nullable=True),
        sa.Column("school_board_district", sa.String(), nullable=True),
        sa.Column("city_council_district", sa.String(), nullable=True),
        sa.Column("municipal_school_board_district", sa.String(), nullable=True),
        sa.Column("water_board_district", sa.String(), nullable=True),
        sa.Column("super_council_district", sa.String(), nullable=True),
        sa.Column("super_commissioner_district", sa.String(), nullable=True),
        sa.Column("super_school_board_district", sa.String(), nullable=True),
        sa.Column("fire_district", sa.String(), nullable=True),
        sa.Column("municipality", sa.String(), nullable=True),
        sa.Column("combo", sa.String(), nullable=True),
        sa.Column("land_lot", sa.String(), nullable=True),
        sa.Column("land_district", sa.String(), nullable=True),
        sa.Column("registration_date", sa.String(), nullable=True),
        sa.Column("race", sa.String(), nullable=True),
        sa.Column("gender", sa.String(), nullable=True),
        sa.Column("last_modified_date", sa.String(), nullable=True),
        sa.Column("date_of_last_contact", sa.String(), nullable=True),
        sa.Column("last_party_voted", sa.String(), nullable=True),
        sa.Column("last_vote_date", sa.String(), nullable=True),
        sa.Column("voter_created_date", sa.String(), nullable=True),
        sa.Column("mailing_street_number", sa.String(), nullable=True),
        sa.Column("mailing_street_name", sa.String(), nullable=True),
        sa.Column("mailing_apt_unit_number", sa.String(), nullable=True),
        sa.Column("mailing_city", sa.String(), nullable=True),
        sa.Column("mailing_zipcode", sa.String(), nullable=True),
        sa.Column("mailing_state", sa.String(), nullable=True),
        sa.Column("mailing_country", sa.String(), nullable=True),
        sa.Column("geocode_status", sa.String(), nullable=True),
        sa.Column("geocode_match_type", sa.String(), nullable=True),
        sa.Column("geocode_matched_address", sa.String(), nullable=True),
        sa.Column("geocode_longitude", sa.Float(), nullable=True),
        sa.Column("geocode_latitude", sa.Float(), nullable=True),
        sa.Column("geocode_tigerline_id", sa.String(), nullable=True),
        sa.Column("geocode_tigerline_side", sa.String(), nullable=True),
        sa.Column("geocode_state_fips", sa.String(), nullable=True),
        sa.Column("geocode_county_fips", sa.String(), nullable=True),
        sa.Column("geocode_tract", sa.String(), nullable=True),
        sa.Column("geocode_block", sa.String(), nullable=True),
        sa.Column(
            "geom",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.Column("usps_validation_status", sa.String(), nullable=True),
        sa.Column("usps_validated_street_address", sa.String(), nullable=True),
        sa.Column("usps_validated_city", sa.String(), nullable=True),
        sa.Column("usps_validated_state", sa.String(), nullable=True),
        sa.Column("usps_validated_zipcode", sa.String(), nullable=True),
        sa.Column("usps_validated_zipplus4", sa.String(), nullable=True),
        sa.Column("usps_delivery_point", sa.String(), nullable=True),
        sa.Column("usps_carrier_route", sa.String(), nullable=True),
        sa.Column("usps_dpv_confirmation", sa.String(), nullable=True),
        sa.Column("usps_business", sa.String(), nullable=True),
        sa.Column("usps_vacant", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("voter_registration_number"),
    )
    op.create_index("idx_voter_county", "voters", ["county"], unique=False)
    op.create_index("idx_voter_county_precinct", "voters", ["county_precinct"], unique=False)
    op.create_index("idx_voter_geocode_status", "voters", ["geocode_status"], unique=False)
    op.create_index("idx_voter_usps_validation", "voters", ["usps_validation_status"], unique=False)
    # Note: idx_voters_geom spatial index is automatically created by GeoAlchemy2 Geometry column
    op.create_index(op.f("ix_voters_geocode_status"), "voters", ["geocode_status"], unique=False)
    op.create_index(
        op.f("ix_voters_usps_validation_status"), "voters", ["usps_validation_status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_voters_usps_validation_status"), table_name="voters")
    op.drop_index(op.f("ix_voters_geocode_status"), table_name="voters")
    # Note: idx_voters_geom spatial index is automatically dropped when voters table is dropped
    op.drop_index("idx_voter_usps_validation", table_name="voters")
    op.drop_index("idx_voter_geocode_status", table_name="voters")
    op.drop_index("idx_voter_county_precinct", table_name="voters")
    op.drop_index("idx_voter_county", table_name="voters")
    op.drop_table("voters")
    # ### end Alembic commands ###
