"""Add county_commission_districts table for spatial analysis

Revision ID: 5c6d93e0e85d
Revises: 0b5f9c2d8e41
Create Date: 2026-02-04 15:37:41.000537

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = "5c6d93e0e85d"
down_revision: Union[str, Sequence[str], None] = "0b5f9c2d8e41"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "county_commission_districts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("district_id", sa.String(length=10), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("rep_name", sa.String(length=100), nullable=True),
        sa.Column("party", sa.String(length=50), nullable=True),
        sa.Column("district_url", sa.String(length=255), nullable=True),
        sa.Column("email", sa.String(length=100), nullable=True),
        sa.Column("photo_url", sa.String(length=255), nullable=True),
        sa.Column("rep_name_2", sa.String(length=100), nullable=True),
        sa.Column("object_id", sa.Integer(), nullable=True),
        sa.Column("global_id", sa.String(length=100), nullable=True),
        sa.Column("creation_date", sa.DateTime(), nullable=True),
        sa.Column("creator", sa.String(length=100), nullable=True),
        sa.Column("edit_date", sa.DateTime(), nullable=True),
        sa.Column("editor", sa.String(length=100), nullable=True),
        sa.Column(
            "geom",
            geoalchemy2.types.Geometry(
                geometry_type="POLYGON",
                srid=4326,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_district_geom",
        "county_commission_districts",
        ["geom"],
        unique=False,
        postgresql_using="gist",
    )
    op.create_index("idx_district_name", "county_commission_districts", ["name"], unique=False)
    op.create_index(
        op.f("ix_county_commission_districts_district_id"),
        "county_commission_districts",
        ["district_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_county_commission_districts_district_id"), table_name="county_commission_districts"
    )
    op.drop_index("idx_district_name", table_name="county_commission_districts")
    op.drop_index(
        "idx_district_geom", table_name="county_commission_districts", postgresql_using="gist"
    )
    op.drop_table("county_commission_districts")
    # ### end Alembic commands ###
